import React, { useState, useEffect } from 'react';
import { Thermometer, Droplets, Wind, BatteryCharging, ShieldCheck, Cpu } from 'lucide-react';
import SensorCard from '../components/SensorCard';
import AlertPanel from '../components/AlertPanel';

export default function Dashboard({ socket, telemetryList, alerts, devices }) {
  const activeDevice = devices[0] || { id: 'AGRISEAL-NODE-0001', name: 'Shimla Transit Sensor 1' };
  const latest = telemetryList[0] || {
    t: 4.1,
    h: 88.5,
    e: 14.2,
    soc: 92,
    idx: 18,
    dev: activeDevice.id,
    verified: true,
    hash: '8f4c2810a95e7c3b10294812fdeea341b5902184cf0128492049102948192049',
  };

  return (
    <div>
      {/* Top Welcome / Status Banner */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.75rem' }}>
        <div>
          <h2>Consignment Telemetry Live Monitor</h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginTop: '0.25rem' }}>
            Real-time IoT cryptographic feed for active consignment <span className="mono" style={{ color: 'var(--emerald-400)' }}>SHIP-2026-0001</span>
          </p>
        </div>
        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <div className="glass-panel" style={{ padding: '0.5rem 1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.82rem' }}>
            <Cpu size={16} style={{ color: 'var(--cyan-500)' }} />
            <span>Active Node: <strong className="mono">{latest.dev}</strong></span>
          </div>
        </div>
      </div>

      {/* Metrics Row */}
      <div className="metrics-grid">
        <SensorCard
          title="Cargo Temperature"
          value={latest.t !== undefined ? latest.t : '--'}
          unit="°C"
          icon={Thermometer}
          colorClass={latest.t > 8 ? 'val-rose' : latest.t > 6 ? 'val-amber' : 'val-emerald'}
          statusText={latest.t > 8 ? 'Breach Risk' : 'Optimal Cold'}
          subtext="Target: 0°C to 4°C"
        />
        <SensorCard
          title="Relative Humidity"
          value={latest.h !== undefined ? latest.h : '--'}
          unit="% RH"
          icon={Droplets}
          colorClass="val-cyan"
          statusText="Grade A Freshness"
          subtext="Target: 85% - 95%"
        />
        <SensorCard
          title="Ethylene Gas"
          value={latest.e !== undefined ? latest.e : '--'}
          unit="ppm"
          icon={Wind}
          colorClass={latest.e > 50 ? 'val-rose' : 'val-amber'}
          statusText={latest.e > 50 ? 'Spoilage Accelerating' : 'Low Ripening'}
          subtext="Threshold: < 50 ppm"
        />
        <SensorCard
          title="Node Battery (SoC)"
          value={latest.soc !== undefined ? latest.soc : '--'}
          unit="%"
          icon={BatteryCharging}
          colorClass="val-emerald"
          statusText="Solar Harvester Active"
          subtext="Est. Reserve: 45 Days"
        />
      </div>

      {/* Grid: Live Telemetry Stream + Alerts */}
      <div className="dashboard-grid">
        {/* Left Column: Live Block Stream */}
        <div className="glass-panel" style={{ padding: '1.5rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
            <div>
              <h3>Edge Sensor Hash Stream</h3>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                Immutable sequential blocks generated by onboard ESP32 SHA-256 micro-engine
              </p>
            </div>
            <span className="verified-badge">
              <ShieldCheck size={14} /> Chain Validated
            </span>
          </div>

          <div style={{ overflowX: 'auto' }}>
            <table className="telemetry-table">
              <thead>
                <tr>
                  <th>Seq #</th>
                  <th>Timestamp</th>
                  <th>Temp</th>
                  <th>Humidity</th>
                  <th>Ethylene</th>
                  <th>SHA-256 Block Digest</th>
                  <th>State</th>
                </tr>
              </thead>
              <tbody>
                {telemetryList.slice(0, 10).map((row, idx) => (
                  <tr key={idx}>
                    <td className="mono" style={{ fontWeight: 600 }}>#{row.idx || idx + 1}</td>
                    <td style={{ color: 'var(--text-secondary)' }}>
                      {row.receivedAt ? new Date(row.receivedAt).toLocaleTimeString() : 'Just now'}
                    </td>
                    <td style={{ fontWeight: 600 }}>{row.t}°C</td>
                    <td>{row.h}%</td>
                    <td>{row.e} ppm</td>
                    <td>
                      <span className="hash-pill">
                        {row.hash ? `${row.hash.slice(0, 10)}...${row.hash.slice(-6)}` : 'e3b0c442...b855'}
                      </span>
                    </td>
                    <td>
                      <span className="verified-badge">
                        <ShieldCheck size={12} /> OK
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Right Column: SLA Breaches & Alerts */}
        <div>
          <AlertPanel alerts={alerts} />
          
          {/* Quick Hardware Spec Box */}
          <div className="glass-panel" style={{ padding: '1.25rem', marginTop: '1.5rem' }}>
            <h4 style={{ marginBottom: '0.5rem', color: 'var(--text-secondary)' }}>Hardware Node Telemetry</h4>
            <div style={{ fontSize: '0.82rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: 'var(--text-muted)' }}>Radio Uplink</span>
                <span className="mono" style={{ color: 'var(--cyan-500)' }}>4G LTE-M / NB-IoT</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: 'var(--text-muted)' }}>Cryptographic Element</span>
                <span className="mono">ATECC608A (Hardware Root)</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: 'var(--text-muted)' }}>Local Offline Buffer</span>
                <span className="mono">16 MB SPI Flash (~16k records)</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ color: 'var(--text-muted)' }}>Tamper Switch</span>
                <span style={{ color: 'var(--emerald-400)', fontWeight: 600 }}>ARMED & INTACT</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
